spring:
  profiles:
    active: dev

server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

hubspot:
  api:
    key: ${HUBSPOT_API_KEY}

crypto:
  secret-key: ${CRYPTO_SECRET_KEY} 