spring:
  profiles:
    active: dev

server:
  port: 8080

logging:
  level:
    root: INFO
    com.hubspot: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method